name: CachePurge

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  purge:
    name: Purge
    runs-on: ubuntu-latest
    steps:
      - name: Purge caches
        uses: MyAlbum/purge-cache@v1
        with:
          max-age: 172800 # 2 days
          debug: true
